### ISSUE TITLE
PB de deploys. 

### ISSUE THREAD

**Issue by Sn0wAlice** [Aptura/ApturaMkDocs#2]
ton runner est pas connu par github. c'est le nom qui doit pas etre bon. utilise un tags pour tester dans le blank.yml

**Comment by Sn0wAlice** [comment]
genre: 
```
runs-on: x64
```
ou autre tags custom que t'as mis

**Comment by Sn0wAlice** [comment]
a ok lol t'avais jsute pas up le runner XD

**Comment by Aptura** [comment]
Voila :P 
J'ai retenus pour la grande majorité donc :P

**Comment by Sn0wAlice** [comment]
:)

**Comment by Aptura** [comment]
Donc attend normalement j'ai tout qui est ok mais je sais pas quoi faire now :')

**Comment by Sn0wAlice** [comment]
regarde les logs de build, par rapport aux commandes ecrite dedant et ce que ça a donné dans la machine

apres, bha il faut modifier le blank.yml pour que sa `mkdocs build` et déplace nos données

**Comment by Aptura** [comment]
Ah ouais merde là je suis dupère xD
Go to read the docs and tutorial !

**Comment by Sn0wAlice** [comment]
Avant: 
```yml

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
```


Apres: 
```

      # Runs a single command using the runners shell
      - name: ICI JE BUILD
        run: COMMANDE SHELL DE BUILD

      # Runs a set of commands using the runners shell
      - name: ICI JE DEPLACE
        run: HUMMM SUREMENT UNE COMMANDE mv . .

```
